### ISSUE TITLE
Changes to the footer

### ISSUE THREAD

**Issue by seancdavis** [rcayabyab/seh_0216#1]
- "SmartHealth Today" header needs to be removed.
- "Social" header needs to be removed.
- Social icons need to be moved under SHT logo.
- SMT logo should be moved up so top of "sun" aligns with top of headlines in the rest of the footer
- Social icons – bottom of icons should line up with the bottom of the "learn more" button under SEP’s footer.

**Comment by hungrymedia** [comment]
@seancdavis @rcayabyab  Updated files attached.
[build.zip](https://github.com/rcayabyab/seh_0216/files/542171/build.zip)

**Comment by hungrymedia** [comment]
@rcayabyab please to grant me write access to this repo when you return. thx

**Comment by seancdavis** [comment]
@rcayabyab: You should also consider making these repositories private. :)
